import { describe, it, expect, vi } from "vitest";
import { 
  isImageGenerationRequest, 
  isTextRefusalForImage, 
  isPlausiblyImageRequest 
} from "../../src/utils/imageIntent";

describe("Image Generation Intent Detection & Safety Net Tests", () => {
  describe("Unit Tests: isImageGenerationRequest()", () => {
    const testCases: { prompt: string; expected: boolean; category: string }[] = [
      // 1-5: Hinglish without explicit image keywords ("flying aeroplane" regression cases)
      { prompt: "flying aeroplane banao", expected: true, category: "Hinglish implicit noun + banao" },
      { prompt: "flying aeroplane dikhao", expected: true, category: "Hinglish implicit noun + dikhao" },
      { prompt: "flying aeroplane dikha do", expected: true, category: "Hinglish implicit noun + dikha do" },
      { prompt: "flying aeroplane bnaa do", expected: true, category: "Hinglish implicit noun + bnaa do" },
      { prompt: "aeroplane chaiye", expected: true, category: "Hinglish implicit noun + chaiye" },

      // 6-10: Hinglish drawing/sketching/designing verbs
      { prompt: "dragon drawing karo", expected: true, category: "Hinglish drawing karo" },
      { prompt: "superhero sketch karo", expected: true, category: "Hinglish sketch karo" },
      { prompt: "space rocket design karo", expected: true, category: "Hinglish design karo" },
      { prompt: "sunset ka scene dikhado", expected: true, category: "Hinglish dikhado" },
      { prompt: "car photo chaiye", expected: true, category: "Hinglish photo chaiye" },

      // 11-15: English phrasings without "of" or explicit "image"
      { prompt: "show me a flying aeroplane", expected: true, category: "English show me a <noun>" },
      { prompt: "what does a flying aeroplane look like", expected: true, category: "English what does <noun> look like" },
      { prompt: "draw a cat on the moon", expected: true, category: "English draw a <noun>" },
      { prompt: "make a picture of a sunset", expected: true, category: "English make a picture" },
      { prompt: "create a 3d render of a cybernetic tiger", expected: true, category: "English 3d render of" },

      // 16-19: Negative filter tests (should NOT trigger image generation)
      { prompt: "draw conclusion from the data", expected: false, category: "Negative phrase: draw conclusion" },
      { prompt: "what are the drawbacks of solar energy", expected: false, category: "Negative phrase: drawbacks" },
      { prompt: "pasta kaise banao", expected: false, category: "Hinglish recipe question (kaise banao)" },
      { prompt: "resume kaise banao", expected: false, category: "Hinglish guide question (kaise banao)" },
    ];

    testCases.forEach(({ prompt, expected, category }) => {
      it(`should return ${expected} for '${prompt}' [${category}]`, () => {
        expect(isImageGenerationRequest(prompt)).toBe(expected);
      });
    });
  });

  describe("Unit Tests: isTextRefusalForImage()", () => {
    it("should accurately identify refusal phrases in AI replies", () => {
      const refusalTexts = [
        "I'm sorry, as a text-based AI, I can't generate images directly.",
        "As an AI text model, I am unable to create visual content.",
        "I cannot actually generate images, but I can describe a flying aeroplane.",
        "I don't have the ability to generate images.",
        "I am unable to create an image of a cat in space."
      ];

      refusalTexts.forEach(text => {
        expect(isTextRefusalForImage(text)).toBe(true);
      });
    });

    it("should return false for valid informative AI replies", () => {
      const validTexts = [
        "An aeroplane flies using aerodynamic lift generated by wings.",
        "Here is a summary of the key concepts from your textbook.",
        "To solve this calculus problem, first differentiate with respect to x."
      ];

      validTexts.forEach(text => {
        expect(isTextRefusalForImage(text)).toBe(false);
      });
    });
  });

  describe("Integration Test: Auto-Correction Safety Net Flow", () => {
    it("should silently catch refusal text reply and re-route to image generation pipeline", async () => {
      const userPrompt = "flying aeroplane dikhao";
      const refusalReply = "I'm sorry, as a text-based AI, I can't generate images.";

      // Mock image generation endpoint handler
      const mockGenerateImageApi = vi.fn().mockResolvedValue({
        ok: true,
        json: async () => ({ imageUrl: "https://images.unsplash.com/photo-flying-aeroplane.jpg" })
      });

      // Simulate the handleSendAI response interceptor pipeline logic
      const processResponse = async (prompt: string, aiTextReply: string) => {
        // Step 1: Detect refusal
        if (isTextRefusalForImage(aiTextReply) && isPlausiblyImageRequest(prompt)) {
          // Step 2: Auto-reroute transparently to image generation
          const imgRes = await mockGenerateImageApi({ prompt });
          const imgData = await imgRes.json();
          return {
            text: "",
            image: imgData.imageUrl,
            autoCorrected: true
          };
        }
        return { text: aiTextReply, image: undefined, autoCorrected: false };
      };

      const result = await processResponse(userPrompt, refusalReply);

      // Assertions
      expect(mockGenerateImageApi).toHaveBeenCalledWith({ prompt: userPrompt });
      expect(result.autoCorrected).toBe(true);
      expect(result.text).toBe(""); // Text refusal discarded
      expect(result.image).toBe("https://images.unsplash.com/photo-flying-aeroplane.jpg");
    });
  });
});
